[package]
name = "font-kit"
version = "0.14.3"
authors = ["Patrick Walton <pcwalton@mimiga.net>"]
description = "A cross-platform font loading library"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/servo/font-kit"
homepage = "https://github.com/servo/font-kit"
exclude = ["resources/**"]
edition = "2018"
rust-version = "1.77"

[features]
default = ["source"]
loader-freetype = ["freetype-sys"]
loader-freetype-default = ["loader-freetype"]
source-fontconfig = ["yeslogic-fontconfig-sys"]
source-fontconfig-dlopen = ["yeslogic-fontconfig-sys/dlopen"]
source-fontconfig-default = ["source-fontconfig"]
source = []

[dependencies]
bitflags = "2.4"
byteorder = "1.2"
float-ord = "0.3"
libc = "0.2"
log = "0.4.4"
pathfinder_geometry = "0.5"
pathfinder_simd = "0.5.5"
freetype-sys = { version = "0.23", optional = true }

[dependencies.yeslogic-fontconfig-sys]
version = "6.0"
optional = true

[dev-dependencies]
clap = "4"
colored = "2"
pbr = "1.0"
prettytable-rs = "0.10"

[target.'cfg(target_family = "windows")'.dependencies]
dwrote = { version = "^0.11.3", default-features = false }

[target.'cfg(target_family = "windows")'.dependencies.winapi]
version = "0.3"
features = ["dwrite", "minwindef", "sysinfoapi", "winbase", "winnt"]

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
objc2-core-foundation = { git = "https://github.com/madsmtm/objc2.git", rev = "0dc236c0e186ed29991798d2a6ff5cdc595b2ffa", default-features = false, features = [
    "std",
    "CFArray",
    "CFCGTypes",
    "CFData",
    "CFDictionary",
    "CFNumber",
    "CFString",
    "CFURL",
] }
objc2-core-graphics = { git = "https://github.com/madsmtm/objc2.git", rev = "0dc236c0e186ed29991798d2a6ff5cdc595b2ffa", default-features = false, features = [
    "std",
    "CGAffineTransform",
    "CGBitmapContext",
    "CGColorSpace",
    "CGContext",
    "CGFont",
    "CGImage",
    "CGPath",
] }
objc2-core-text = { git = "https://github.com/madsmtm/objc2.git", rev = "0dc236c0e186ed29991798d2a6ff5cdc595b2ffa", default-features = false, features = [
    "std",
    "objc2-core-graphics",
    "CTFont",
    "CTFontCollection",
    "CTFontDescriptor",
    "CTFontManager",
    "CTFontTraits",
] }

[target.'cfg(not(any(target_family = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
freetype-sys = "0.23"

[target.'cfg(not(any(target_family = "windows", target_os = "macos", target_os = "ios", target_arch = "wasm32", target_env = "ohos")))'.dependencies]
yeslogic-fontconfig-sys = "6.0"

[target.'cfg(not(any(target_arch = "wasm32", target_family = "windows", target_os = "android", target_env = "ohos")))'.dependencies]
dirs = "6.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
walkdir = "2.1"
